return {
	package = {
		name = "hop",
		version = "0.2.0",
		dependencies = {
			["lute"] = {
				rev = "v1.0.1-nightly.20260924",
				sourceKind = "github",
				source = "https://github.com/luau-lang/lute",
			},
			["FlipbookBatteries"] = {
				rev = "v0.12.0",
				sourceKind = "github",
				source = "https://github.com/flipbook-labs/flipbook-batteries",
			},
		},
		dev_dependencies = {},
	},
}
